
server:
  port: 8082

spring:
  application:
    name: CUSTOMER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb

# Eureka client configuration removed

logging:
  level:
    com.zapcom.customerservice: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
