
server:
  port: 8082

spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.zapcom.customerservice: DEBUG
