
server:
  port: 8082

spring:
  application:
    name: CUSTOMER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    com.zapcom.customerservice: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
