
server:
  port: 8080

spring:
  application:
    name: gateway-service
  # Add Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}
            - name: RequestLoggingFilter
            - name: ResponseTransformFilter
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /customers/${segment}
            - name: JwtAuthFilter
            - name: RequestLoggingFilter
            - name: ResponseTransformFilter
            # Add rate limiter filter to the customer service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,routes
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

# Resilience4j Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      defaultCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED
  timelimiter:
    instances:
      defaultCircuitBreaker:
        timeout-duration: 5s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty: INFO
    com.zapcom: DEBUG

jwt:
  secret: veryLongAndSecureSecretKeyForAuthServiceSigning123!@#
  expiration: 3600 # 1 hour in seconds

# Static service discovery configuration
services:
  auth-service:
    url: http://localhost:8081
  customer-service:
    url: http://localhost:8082
